name: Build and Release

on:
  push:
    tags:
      - "v*" # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build binaries
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [windows, linux, darwin]
        arch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21 # Specify your Go version

      - name: Build binary
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o build/${{ matrix.os }}-${{ matrix.arch }}/app .
        env:
          CGO_ENABLED: 0

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: |
          gh auth setup-git
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} ./build/** --title "Release ${{ github.ref_name }}" --notes "Automatically generated release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
